#!/usr/bin/env bash

execute() {
#  load_config "$@"
  load_lib
  #  debug 'post load_lib'
  #  debug "PYTIME_PROJECT_DIR: $PYTIME_PROJECT_DIR"
  activenvate
  run_pythee "$@"
}

load_lib() {
  lib="$(realpath "$(dirname "${BASH_SOURCE[0]}")/../components/pytime.lib.sh")"
  # shellcheck disable=SC1090
  . "$lib" && return 0
  echo "Failed to load lib: $lib"
  exit 1
}

#load_config() {
#  #  CONFILE="${BASH_SOURCE[0]%.sh}.conf"
#  CONFILE=$1
#  echo "Load CONFILE: ${CONFILE}"
#  # shellcheck disable=SC1090
#  . "${CONFILE}" && return 0
#  echo "${BASH_SOURCE[0]}; Failed to load lib: ${CONFILE}"
#  exit 1
#}

execute "$@"
